# Section 2: about Tensorflow


Graph based. 

Compare the following segments: 


In [2]:
import numpy as np
import tensorflow as tf

In [4]:
matrix_a = np.random.rand(2,3)
matrix_b = np.random.rand(2,3)
matrix_c = matrix_a + matrix_b
print(matrix_a)
print(matrix_b)
print(matrix_c)



[[ 0.36068616  0.78508744]
 [ 0.95798618  0.09011121]]
[[ 0.27576617  0.68573616]
 [ 0.20035914  0.91171309]]
[[ 0.63645232  1.4708236 ]
 [ 1.15834532  1.0018243 ]]


In [13]:
# Example from here: https://www.tensorflow.org/api_docs/python/tf/Session
# Build a graph.
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

# Launch the graph in a session.
sess = tf.Session()
print(a)
print(b)
print(c)
# Evaluate the tensor `c`.
print(sess.run(c))


Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("Const_3:0", shape=(), dtype=float32)
Tensor("mul_1:0", shape=(), dtype=float32)
30.0


In [5]:
matrix_a = tf.Variable(tf.random_uniform([2, 3]), name="matrix_a")
matrix_b = tf.Variable(tf.random_uniform([2, 3]), name="matrix_b")
matrix_c = matrix_a + matrix_b

print(matrix_a)
print(matrix_b)
print(matrix_c)


<tf.Variable 'matrix_a:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'matrix_b:0' shape=(2, 3) dtype=float32_ref>
Tensor("add:0", shape=(2, 3), dtype=float32)


Looks like we have some variables, instead of values. Let's see what's in them: 


In [6]:
init = tf.global_variables_initializer() # https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer
sess = tf.Session() # https://www.tensorflow.org/api_docs/python/tf/Session
sess.run(init)
print(sess.run(matrix_a))
print(sess.run(matrix_b))
print(sess.run(matrix_c))


[[ 0.14429128  0.16543818  0.54946935]
 [ 0.89654994  0.6893028   0.65029776]]
[[ 0.73194873  0.73769426  0.99907053]
 [ 0.59399199  0.57328951  0.00344467]]
[[ 0.87624002  0.90313244  1.54853988]
 [ 1.49054193  1.26259232  0.65374243]]


### Placeholders
Now you know how to play with static data we are going to make it a little bit more interesting, and start working with placeholders. 

Let's say we want to add one to each element in the following matrix: 
XXXX


In [11]:
our_variable = np.array([[1,2],[3,4],[5,6]])
to_add_matrix = np.ones([3,2])
print(our_variable)
print(to_add_matrix)
result = our_variable + to_add_matrix
print(result)

[[1 2]
 [3 4]
 [5 6]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


In [14]:
# Now with Tensorflow this would look like: 
tf.ones # https://www.tensorflow.org/api_guides/python/constant_op

<function tensorflow.python.ops.array_ops.ones>