# The Dataset Driven Approach to Building Neural Networks with Tensorflow 

Thank you for downloading this notebook. This means you are subscribed to my first online course: a dataset driven approach to building neural networks with Tensorflow. 


## Section 1: solving public datasets and your own sets: is deep learning a science or an art?

Reference to this [paper from 1994](http://dl.acm.org/citation.cfm?id=181522). 


## Section 2: why we use Docker, and installation instruction



## Installation
We use Docker, super awesome stuff

### Windows 10

### OSX
 
### Linux

### Windows 7



## Section 3: where to find the Jupyter notebook, code, etc. 

## Section 4: Understanding Tensorflow

Tensorflow is a XXX based tool. Normally in Python everything you type with variables is evaluated immediately: 


In [1]:
a = 1.0
b = 2.0
c = a + b
print(c)

3.0


In Tensorflow this is different: you first define the variables in a graph, and the operations in this graph. You then 'compile' and build up this graph, and evaluate it in a session you defined:


In [2]:
import tensorflow as tf
# Example from here: https://www.tensorflow.org/api_docs/python/tf/Session
# Build a graph.
a = tf.constant(1.0)
b = tf.constant(2.0)
c = a * b
print(a)
print(b)
print(c)

# Launch the graph in a session.
sess = tf.Session()
# Evaluate the tensor `c`.
print(sess.run(c))



Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("mul:0", shape=(), dtype=float32)
2.0


In [3]:
sess.run?

In [4]:
import numpy as np


In [5]:
matrix_a = np.random.rand(2,3)
matrix_b = np.random.rand(2,3)
matrix_c = matrix_a + matrix_b
print(matrix_a)
print(matrix_b)
print(matrix_c)




[[ 0.70393472  0.51152581  0.58675583]
 [ 0.91018351  0.56399951  0.44546657]]
[[ 0.39655651  0.25052009  0.85010918]
 [ 0.76321046  0.92673495  0.86829131]]
[[ 1.10049123  0.76204589  1.436865  ]
 [ 1.67339397  1.49073446  1.31375789]]


In [6]:
matrix_a = tf.Variable(tf.random_uniform([2, 3]), name="matrix_a")
matrix_b = tf.Variable(tf.random_uniform([2, 3]), name="matrix_b")
matrix_c = matrix_a + matrix_b

print(matrix_a)
print(matrix_b)
print(matrix_c)
try:
    print(sess.run(matrix_a))
    print(sess.run(matrix_b))
    print(sess.run(matrix_c))
except Exception as e:
    print("EXCEPTION!")
    print(e)



<tf.Variable 'matrix_a:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'matrix_b:0' shape=(2, 3) dtype=float32_ref>
Tensor("add:0", shape=(2, 3), dtype=float32)
EXCEPTION!
Attempting to use uninitialized value matrix_a
	 [[Node: _retval_matrix_a_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](matrix_a)]]


Looks like Tensorflow does not like what we are doing. Before using anything from the graph you have to initialise the graph:

In [7]:
init = tf.global_variables_initializer() # https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer
print(init)
sess = tf.Session() # https://www.tensorflow.org/api_docs/python/tf/Session
sess.run(init)
print(sess.run(matrix_a))
print(sess.run(matrix_b))
print(sess.run(matrix_c))

name: "init"
op: "NoOp"
input: "^matrix_a/Assign"
input: "^matrix_b/Assign"

[[ 0.74558568  0.69464195  0.53896284]
 [ 0.97363114  0.30603969  0.69910371]]
[[ 0.39540875  0.32313693  0.55544686]
 [ 0.4022845   0.3200599   0.35239327]]
[[ 1.14099443  1.01777887  1.0944097 ]
 [ 1.37591565  0.62609959  1.05149698]]


### Placeholders
Now you know how to play with static data we are going to make it a little bit more interesting, and start working with placeholders. 

Let's say we want to add one to each element in the following matrix: 

\begin{matrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{matrix}

Here is how we do this with numpy: 


In [8]:
our_matrix = np.array([[1,2],[3,4],[5,6]])
to_add_matrix = np.ones([3,2])
result_matrix = our_matrix + to_add_matrix
print(our_matrix)
print(to_add_matrix)
print(result_matrix)

[[1 2]
 [3 4]
 [5 6]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


In [9]:
# Now with Tensorflow this would look like: 
input_shape = [3,2]
inputplaceholder = tf.placeholder(dtype=tf.int32, shape=input_shape, name="input_placeholder") # https://www.tensorflow.org/api_docs/python/tf/placeholder
print(inputplaceholder)
toadd = tf.ones(input_shape) # https://www.tensorflow.org/api_guides/python/constant_op
try:
    together = inputplaceholder + toadd
    print(together)
except Exception as e:
    print("ERROR!")
    print(e)

## Now correct: 
toadd = tf.ones(input_shape,dtype=tf.int32)
together = inputplaceholder + toadd
print(together)

init = tf.global_variables_initializer() # https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer
sess = tf.Session() # https://www.tensorflow.org/api_docs/python/tf/Session
sess.run(init)
result = sess.run(together, feed_dict={inputplaceholder: our_matrix})
print('-'*10)
print(result)









Tensor("input_placeholder:0", shape=(3, 2), dtype=int32)
ERROR!
Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("ones:0", shape=(3, 2), dtype=float32)'
Tensor("add_2:0", shape=(3, 2), dtype=int32)
----------
[[2 3]
 [4 5]
 [6 7]]



https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/dtypes.py
The following `DType` objects are defined:
  * `tf.float16`: 16-bit half-precision floating-point.
  * `tf.float32`: 32-bit single-precision floating-point.
  * `tf.float64`: 64-bit double-precision floating-point.
  * `tf.bfloat16`: 16-bit truncated floating-point.
  * `tf.complex64`: 64-bit single-precision complex.
  * `tf.complex128`: 128-bit double-precision complex.
  * `tf.int8`: 8-bit signed integer.
  * `tf.uint8`: 8-bit unsigned integer.
  * `tf.uint16`: 16-bit unsigned integer.
  * `tf.int16`: 16-bit signed integer.
  * `tf.int32`: 32-bit signed integer.
  * `tf.int64`: 64-bit signed integer.
  * `tf.bool`: Boolean.
  * `tf.string`: String.
  * `tf.qint8`: Quantized 8-bit signed integer.
  * `tf.quint8`: Quantized 8-bit unsigned integer.
  * `tf.qint16`: Quantized 16-bit signed integer.
  * `tf.quint16`: Quantized 16-bit unsigned integer.
  * `tf.qint32`: Quantized 32-bit signed integer.
  * `tf.resource`: Handle to a mutable resource.
  * `tf.variant`: Values of arbitrary types.


Now we did this operation once, but if we want to perform this operation with multiple types of input data we keep defining what the input is. Instead we define what we have as input, and a series of operations on this data:


