# The Dataset Driven Approach to Building Neural Networks with TensorFlow 

Welcome to the first section fo the course "The Dataset Driven Approach to Building Neural Networks with Tensorflow". In this section you are going to learn: 
- That deep learning both a science and an art
- Why we use Docker, and how to get access to all the code
- How to use a Jupyter notebook
- What Tensorflow is and how you work with it


## Video 1: solving public datasets and your own sets: is deep learning a science or an art? ( 3 mins) 
People often discuss whether being good at deep learning requires a lot of knowledge (like a scientist), or requires a lot of practice (like an artist). With these questions the answer always is: you need to have a combination of both. Only solving a lot of datasets will give you the intuition to build neural networks for new datasets. However, if you want to solve your problems better than anyone else, you will need to know exactly why you apply certain techniques in neural networks. 

In a [scientific paper from 1994](http://dl.acm.org/citation.cfm?id=181522) scientists already see this problem coming. Now deep learning is very popular many people want to use it on their own datasets. Many will achieve results that are satisfactory, but only really understanding the problem allows you to solve the problem. 

In this course you will learn to be a network artist and a network scientist at the same time.  practicing on many datasets will give you a good intuition in what techniques you can apply for certain problems. We discuss what techniques do, and immediately use this to solve datasets. After you are done with the course you can revisit the first problems you faced and use the knowledge you gained to solve the first few problems even better!





## Video 2: Why we use Docker, and installation instructions



Often when you follow a course online you need to install many programs before you can finally start programming your coursework. For this course you only need to install one program: **Docker**. 

Docker is a tool which allows you to run an isolated operating system on your computer. It's like you are running a pc, on your pc. You can run a second Windows in Windows, or an Ubuntu (Linux) server under Windows. 

For this course I made a **Docker image** that contains all dependencys you normally would have to install. This means everyone who joins has the same Python version, the same version of Tensorflow, and no problems with libraries. 

Unfortunately, you still need to get one program running before you can start: Docker itself. 

### Installation
The best way to install Docker is by looking at this webpage: https://docs.docker.com/engine/installation/#supported-platforms

I made operating system specific tutorials for you so you can skip irrelevant parts. Note that if you are on Windows 7 you need to install [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/). 



## Video 3: where to find the Jupyter notebook, code, etc. 

Once you install Docker getting started is easy. Open a terminal and verify that typing docker works: 

> `docker`

Next you type
> `docker pull rmeertens/datasetdriventensorflow` 

This command will take a while, as you download an image with an operating system, Tensorflow, and several libraries you need for the course. Although it might be a little bit of a hassle now I found that working with Docker for courses like this significantly improves the experience of people who can follow the course. Installing just one program turns out to be way better than installing the 5 libraries you need during the course. 

As we will be working with data I want you to download this data yourself. Make a folder (workspace) for yourself where you will be following this whole course. Create a folder called "datasets" in this folder. 

Now navigate to this folder in your terminal, and run
> `docker run rmeertens/datasetdriventensorflow` 

Here should be something about mounting a volume to keep your progress, and we have to load the datasets from a volume as I don't want to include these..

## Video 4: Understanding Tensorflow

In the previous video we saw how to work with a Jupyter notebook. Hopefully you succeeded, and you managed to open a notebook. This is the fourth video, where we are going to use the Jupyter notebook you downloaded to understand **Tensorflow**. 

In this video we:
- go over the definition of Tensorflow
- show how simple mathematical operations work in Tensorflow
- use placeholders to bring values outside our Tensorflow graph into the graph
- are going to chain multiple operations together
- are going to inspect our graph

### The definition of Tensorflow

According to https://www.tensorflow.org/
> TensorFlow™ is an open source software library for numerical computation using data flow graphs.

As you are following this course you probably don't know what they mean with this. Don't worry, we will figure it out in this section!

> Nodes in the graph represent mathematical operations, while the graph edges represent the multidimensional data arrays (tensors) communicated between them. 

Wow, this is really abstract. Let's not think about this sentence for now. 

> The flexible architecture allows you to deploy computation to one or more CPUs or GPUs in a desktop, server, or mobile device with a single API.

Oeh, that sounds like something we want to use! I personally love deep learning and neural networks, and having them on my computer, a server, and a mobile phone sounds pretty good. 

Let's dive into the data flow graphs Tensorflow is well known for. Normally in Python everything you type with variables is evaluated immediately. Take a look at this example


In [1]:
a = 1.0
b = 2.0
c = a + b
print(c)


3.0


Tensorflow works a little different. You first define the variables and operations in a graph. You then 'compile' and build up this graph, and evaluate it in a session you defined:


In [4]:
import tensorflow as tf
# Example from here: https://www.tensorflow.org/api_docs/python/tf/Session
# Build a graph.
a = tf.constant(1.0)
b = tf.constant(2.0)
c = a * b
print(a)
print(b)
print(c)

# Launch the graph in a session.
sess = tf.Session()
# Evaluate the tensor `c`.
print(sess.run(c))


Tensor("add_1:0", shape=(), dtype=float32)
3.0


As you can see the variable C is an "operation" with two constants as input: a and b. In an image this looks like this: 
![graph def](illustrations/firstmul.png)

Now let's see what the sess.run function actually does. 

In [5]:
sess.run?

Python is pretty good for mathematical operations, especially if you import the Numpy library: a [package for scientific computing](http://www.numpy.org/). Let's take a look at how you add two random matrices ([arrays with numbers](https://en.wikipedia.org/wiki/Matrix_(mathematics) ))together with numpy: 


In [4]:
import numpy as np
matrix_a = np.random.rand(2,3)
matrix_b = np.random.rand(2,3)
matrix_c = matrix_a + matrix_b
print(matrix_a)
print(matrix_b)
print(matrix_c)

[[ 0.4719133   0.07685149  0.16316068]
 [ 0.29911878  0.34850413  0.23822868]]
[[ 0.8400967   0.04223875  0.57291391]
 [ 0.71931931  0.74987892  0.70417859]]
[[ 1.31200999  0.11909024  0.73607459]
 [ 1.01843808  1.09838305  0.94240727]]


In tensorflow you can define these variables as variables in your computation graph. You can select how they are initialised, and the operations you want to do on this graph: 


In [5]:
matrix_a = tf.Variable(tf.random_uniform([2, 3]), name="matrix_a")
matrix_b = tf.Variable(tf.random_uniform([2, 3]), name="matrix_b")
matrix_c = matrix_a + matrix_b

print(matrix_a)
print(matrix_b)
print(matrix_c)
try:
    print(sess.run(matrix_a))
    print(sess.run(matrix_b))
    print(sess.run(matrix_c))
except Exception as e:
    print("EXCEPTION!")
    print(e)



<tf.Variable 'matrix_a:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'matrix_b:0' shape=(2, 3) dtype=float32_ref>
Tensor("add:0", shape=(2, 3), dtype=float32)
EXCEPTION!
Attempting to use uninitialized value matrix_a
	 [[Node: _retval_matrix_a_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/cpu:0"](matrix_a)]]


Welp: looks like Tensorflow does not like what we are doing. In this case we specified that we wanted to initialise our variables with random values. To do that you have to **initialise** the graph:

In [6]:
init = tf.global_variables_initializer() # https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer
print(init)
sess = tf.Session() # https://www.tensorflow.org/api_docs/python/tf/Session
sess.run(init)
print(sess.run(matrix_a))
print(sess.run(matrix_b))
print(sess.run(matrix_c))

name: "init"
op: "NoOp"
input: "^matrix_a/Assign"
input: "^matrix_b/Assign"

[[ 0.9584837   0.08067548  0.1182915 ]
 [ 0.35739994  0.4036026   0.66941535]]
[[ 0.85512495  0.8112179   0.89441192]
 [ 0.44817352  0.89820468  0.89613581]]
[[ 1.81360865  0.89189339  1.01270342]
 [ 0.80557346  1.30180728  1.56555116]]


Great! It works. The graph that we defined now looks like this: 
![mat add](illustrations/matadd.png)

### Placeholders
Now you know how to play with static data we are going to make it a little bit more interesting, and start working with placeholders. 

Let's say we want to add one to each element in the following matrix: 

\begin{matrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{matrix}

Here is how we do this with numpy: 


In [7]:
our_matrix = np.array([[1,2],[3,4],[5,6]])
to_add_matrix = np.ones([3,2])
result_matrix = our_matrix + to_add_matrix
print(our_matrix)
print(to_add_matrix)
print(result_matrix)

[[1 2]
 [3 4]
 [5 6]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


Now with Tensorflow this would look like this: 

In [8]:

input_shape = [3,2]
inputplaceholder = tf.placeholder(dtype=tf.int32, shape=input_shape, name="input_placeholder") # https://www.tensorflow.org/api_docs/python/tf/placeholder
print(inputplaceholder)
toadd = tf.ones(input_shape) # https://www.tensorflow.org/api_guides/python/constant_op
try:
    together = inputplaceholder + toadd
    print(together)
except Exception as e:
    print("ERROR!")
    print(e)

Tensor("input_placeholder:0", shape=(3, 2), dtype=int32)
ERROR!
Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("ones:0", shape=(3, 2), dtype=float32)'


Welp, an error occured. It looks like the `tf.ones` function expects a `dtype` variable. Let's define that both variables contain integers:

In [9]:
inputplaceholder = tf.placeholder(dtype=tf.int32, shape=input_shape, name="input_placeholder")
toadd = tf.ones(input_shape,dtype=tf.int32)
together = inputplaceholder + toadd
print(together)

init = tf.global_variables_initializer() # https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer
sess = tf.Session() # https://www.tensorflow.org/api_docs/python/tf/Session
sess.run(init)
result = sess.run(together, feed_dict={inputplaceholder: our_matrix})
print('-'*10)
print(result)

Tensor("add_2:0", shape=(3, 2), dtype=int32)
----------
[[2 3]
 [4 5]
 [6 7]]



According to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/dtypes.py
The following `DType` objects are defined:
  * `tf.float16`: 16-bit half-precision floating-point.
  * `tf.float32`: 32-bit single-precision floating-point.
  * `tf.float64`: 64-bit double-precision floating-point.
  * `tf.bfloat16`: 16-bit truncated floating-point.
  * `tf.complex64`: 64-bit single-precision complex.
  * `tf.complex128`: 128-bit double-precision complex.
  * `tf.int8`: 8-bit signed integer.
  * `tf.uint8`: 8-bit unsigned integer.
  * `tf.uint16`: 16-bit unsigned integer.
  * `tf.int16`: 16-bit signed integer.
  * `tf.int32`: 32-bit signed integer.
  * `tf.int64`: 64-bit signed integer.
  * `tf.bool`: Boolean.
  * `tf.string`: String.
  * `tf.qint8`: Quantized 8-bit signed integer.
  * `tf.quint8`: Quantized 8-bit unsigned integer.
  * `tf.qint16`: Quantized 16-bit signed integer.
  * `tf.quint16`: Quantized 16-bit unsigned integer.
  * `tf.qint32`: Quantized 32-bit signed integer.
  * `tf.resource`: Handle to a mutable resource.
  * `tf.variant`: Values of arbitrary types.

Try to keep these datatypes in mind when you are developing your own application!

### Chaining operations
Right now we only made very simple graphs with only one operation. Let's say we want to make a more interesting graph where we apply several operations. To make the graph more clear I will give the operations a name this time. This looks like this in Tensorflow:



In [10]:
tf.add?

In [11]:
our_matrix = np.array([[1,2],[3,4],[5,6]])
print(our_matrix.shape)
inputplaceholder = tf.placeholder(dtype=tf.int32, shape=our_matrix.shape, name="input_placeholder")
toadd1 = tf.ones(input_shape,dtype=tf.int32, name='first_ones')
toadd2 = tf.ones(input_shape,dtype=tf.int32, name='second_ones')
together1 = tf.add(inputplaceholder, toadd1, name='first_addition')
together2 = tf.add(together1, toadd2, name='second_addition')
together3 = tf.add(together2, toadd1, name='last_addition')

(3, 2)


This gives us the following graph:
![bigger graph](illustrations/biggergraph.png)
If we take a sessions and evaluate the result of the last operation while we feed a placeholder every operation to achieve this result is executed in the background: 


In [12]:
init = tf.global_variables_initializer() # https://www.tensorflow.org/api_docs/python/tf/global_variables_initializer
sess = tf.Session() # https://www.tensorflow.org/api_docs/python/tf/Session
sess.run(init)

result = sess.run(together3, feed_dict={inputplaceholder: our_matrix})
print(result)

[[4 5]
 [6 7]
 [8 9]]


### Knowing what's in your graph
Sometimes it can be useful to know what kind of operations are in your graph. You can do this with the following call: 
`print([op.name for op in tf.get_default_graph().get_operations()])`


In [13]:
print([op.name for op in tf.get_default_graph().get_operations()])

['Const', 'Const_1', 'mul', 'random_uniform/shape', 'random_uniform/min', 'random_uniform/max', 'random_uniform/RandomUniform', 'random_uniform/sub', 'random_uniform/mul', 'random_uniform', 'matrix_a', 'matrix_a/Assign', 'matrix_a/read', 'random_uniform_1/shape', 'random_uniform_1/min', 'random_uniform_1/max', 'random_uniform_1/RandomUniform', 'random_uniform_1/sub', 'random_uniform_1/mul', 'random_uniform_1', 'matrix_b', 'matrix_b/Assign', 'matrix_b/read', 'add', 'init', 'input_placeholder', 'ones', 'input_placeholder_1', 'ones_1', 'add_2', 'init_1', 'input_placeholder_2', 'first_ones', 'second_ones', 'first_addition', 'second_addition', 'last_addition', 'init_2']


And sometimes you want to remove everything in your graph and start all over again. You can do this with this piece of code: 

In [14]:
tf.reset_default_graph()

### Conclusion section 1
In this section we talked about the approach we take during this course to learn about neural networks and Tensorflow. We installed Docker and loaded the Jupyter notebook in it. 

In this video you saw that Tensorflow works a bit different than what you normally expect if you use Python. It takes a bit of time and practice to get used to defining graphs, but during this course we will do it very often, so you will become good at it!

In the next section we are going to solve our first dataset: one in which we are going to classify three types of flowers with our first neural network. 
